In [5]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a,b)

[1 2 3 4] [5 6 7 8]


In [8]:
type(a)

numpy.ndarray

In [9]:
print(a+b)
print(a*b)

[ 6  8 10 12]
[ 5 12 21 32]


In [11]:
a2 = np.array([[1,2], [3,4]])
print(a2)

[[1 2]
 [3 4]]


In [12]:
a3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
print(a3.shape) #2,2,2 means 2 2x2 matrices
print(a3.ndim)
print(a3.dtype)

(2, 2, 2)
3
int64


In [16]:
np.arange(10)
np.arange(2,21)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
np.random.randint(1,11, size=(2,3))

array([[ 7,  4,  6],
       [ 8,  6, 10]], dtype=int32)

In [29]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [30]:
print(x+y)

[[ 8 10  6]
 [ 5 12  4]
 [ 5 10  4]]


In [ ]:
print(x@y) #matrix multiplication method1

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [ ]:
np.dot(x,y) #matrix multipliction method2

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [33]:
x.prod()

np.int64(12600)

In [ ]:
x.mean() #mean of all element

np.float64(3.3333333333333335)

In [35]:
x.mean(axis=0) #axis = 0 means mean of each column

array([4., 4., 2.])

In [36]:
x.mean(axis=1) #axis = 1 means mean of each column

array([4., 3., 3.])

In [38]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [39]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25))
print(np.percentile(a, 50))
print(np.percentile(a, 75))

3.0
5.0
7.0


In [51]:
#convert 3x3 matrix to 1x9
print('9x1')
print(y.reshape(9,1))
print('1x9')
print(y.reshape(1,9))

9x1
[[1]
 [8]
 [3]
 [3]
 [7]
 [2]
 [2]
 [5]
 [3]]
1x9
[[1 8 3 3 7 2 2 5 3]]


In [49]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [55]:
print(x[0]) #first row
print(x[0,1]) #first row,second column
print(x[-1])
print(x[-1,0])

[7 2 3]
2
[3 5 1]
3
